#!/bin/bash

echo "=========================================="
echo "🎯 Intention Module - 部署完成"
echo "=========================================="
echo ""
echo "✅ 已创建的文件："
echo ""
echo "📂 模块文件："
echo "   modules/intention/IntentionModule.js      (415 行)"
echo "   modules/intention/config.json"
echo "   modules/intention/schema.json"
echo "   modules/intention/flows.json"
echo "   modules/intention/README.md"
echo "   modules/intention/IMPLEMENTATION.md"
echo "   modules/intention/quickstart.sh"
echo ""
echo "📂 Web界面："
echo "   public/intention-api-docs.html           (1027 行)"
echo ""
echo "📂 API集成："
echo "   server.js                                (已添加7个handler)"
echo ""
echo "📂 数据目录："
echo "   data/intention/                          (已创建)"
echo ""
echo "=========================================="
echo "🚀 启动步骤"
echo "=========================================="
echo ""
echo "1️⃣  重启服务器（加载新模块）："
echo "   pkill -f 'node.*server.js' && node server.js &"
echo ""
echo "2️⃣  等待服务器启动（约3-5秒）"
echo ""
echo "3️⃣  访问Web界面："
echo "   open http://localhost:3000/intention-api-docs.html"
echo ""
echo "4️⃣  测试API："
echo "   curl -X POST http://localhost:3000/api/intention/intention/process \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"type\":\"message\",\"content\":\"打开所有灯\",\"metadata\":{},\"timestamp\":\"'$(date -u +%Y-%m-%dT%H:%M:%S.000Z)'\"}'"
echo ""
echo "=========================================="
echo "📚 核心功能"
echo "=========================================="
echo ""
echo "✅ HTTP Request API - 接收JSON意图数据"
echo "✅ AI自动选择 - Claude/OpenAI/Gemini/DeepSeek"
echo "✅ 意图解析 - 转换为Home Assistant服务调用"
echo "✅ 系统提示词管理 - 支持自定义"
echo "✅ 历史记录 - 保存最近100条"
echo "✅ Web管理界面 - 完整的测试和配置界面"
echo ""
echo "=========================================="
echo "📖 API端点"
echo "=========================================="
echo ""
echo "POST   /api/intention/intention/process       - 处理意图"
echo "GET    /api/intention/intention/history       - 获取历史"
echo "GET    /api/intention/intention/prompt        - 获取提示词"
echo "PUT    /api/intention/intention/prompt        - 保存提示词"
echo "DELETE /api/intention/intention/prompt        - 删除提示词"
echo "GET    /api/intention/intention/ai-provider   - 获取AI配置"
echo "POST   /api/intention/intention/ai-provider   - 设置AI"
echo ""
echo "=========================================="
echo "⚠️  重要提示"
echo "=========================================="
echo ""
echo "1. 确保至少配置一个AI提供商（通过各自的API页面配置凭据）"
echo "2. 服务器必须重启才能加载新模块"
echo "3. 首次使用建议通过Web界面测试功能"
echo ""
echo "📖 详细文档: modules/intention/README.md"
echo "📊 实现细节: modules/intention/IMPLEMENTATION.md"
echo ""
echo "=========================================="
echo "🎉 部署完成！"
echo "=========================================="

